image: node:4.2.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - cd blog
  - npm install hexo-cli -g
  - npm install
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
    - master